# Name of the Workflow
name: CICD

on : push

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v7
  build:
    needs: code
    runs-on: ubuntu-latest
    steps:
      - name: Code Build
        uses: actions/checkout@v7
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Code Test
        uses: actions/checkout@v7
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Code Deployed
        uses: actions/checkout@v7

